version: '3.8'
services:
  app:
    image: eimg/fairway-pwd
    platform: linux/amd64
    container_name: inventory-app
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    working_dir: /var/www/html
    restart: unless-stopped
